### ISSUE TITLE
SRS - External Actor Descriptions

### ISSUE THREAD

**Issue by salterm** [RustVCG/RustVCG#20]
This is very UML-y, but we should go over the "actors" for our project:
Human users
The compiler
ATP

**Comment by VSchuster** [comment]
User: A human user that produces rust code which has a pre-condition/post-condition

**Comment by salterm** [comment]
Yes, forget about ATP/Compiler for users. They're all passive.

**Comment by VSchuster** [comment]
SECTION REMOVED
